"""add merchant identifiers to transactions and recurring

Revision ID: 1f8d70109e12
Revises: 4dd40d9cb455
Create Date: 2026-07-11 23:12:20.805754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f8d70109e12'
down_revision = '4dd40d9cb455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_entity_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_recurring_expenses_merchant_entity_id'), ['merchant_entity_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('merchant_entity_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_merchant_entity_id'), ['merchant_entity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_merchant_entity_id'))
        batch_op.drop_column('merchant_entity_id')
        batch_op.drop_column('merchant_name')

    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_expenses_merchant_entity_id'))
        batch_op.drop_column('merchant_entity_id')

    # ### end Alembic commands ###
