"""envelope allocations, allocation rules, plaid accounts

Revision ID: 4df04abeb39c
Revises: 0211697a8b14
Create Date: 2026-07-09 22:29:48.084363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df04abeb39c'
down_revision = '0211697a8b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plaid_item_id', sa.Integer(), nullable=False),
    sa.Column('plaid_account_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('official_name', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('account_subtype', sa.String(length=50), nullable=True),
    sa.Column('mask', sa.String(length=10), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('available_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('iso_currency_code', sa.String(length=10), nullable=True),
    sa.Column('balance_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaid_account_id')
    )
    op.create_table('allocation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('allocation_type', sa.String(length=20), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['financial_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'goal_id', name='unique_user_goal_rule')
    )
    op.create_table('envelope_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source_transaction_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['financial_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('envelope_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_envelope_allocations_goal_id'), ['goal_id'], unique=False)

    with op.batch_alter_table('financial_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('priority_order', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_financial_goals_linked_account_id', 'plaid_accounts', ['linked_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_goals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_financial_goals_linked_account_id', type_='foreignkey')
        batch_op.drop_column('priority_order')
        batch_op.drop_column('linked_account_id')

    with op.batch_alter_table('envelope_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_envelope_allocations_goal_id'))

    op.drop_table('envelope_allocations')
    op.drop_table('allocation_rules')
    op.drop_table('plaid_accounts')
    # ### end Alembic commands ###
