"""recurring expenses and occurrences

Revision ID: 51606e172557
Revises: e90347e3bffd
Create Date: 2026-07-10 09:40:53.794612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51606e172557'
down_revision = 'e90347e3bffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=False),
    sa.Column('merchant_key', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cadence', sa.String(length=20), nullable=False),
    sa.Column('next_expected_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_expense_occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurring_expense_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('occurred_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['recurring_expense_id'], ['recurring_expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('recurring_expense_occurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_expense_occurrences_recurring_expense_id'), ['recurring_expense_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_expense_occurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_expense_occurrences_recurring_expense_id'))

    op.drop_table('recurring_expense_occurrences')
    op.drop_table('recurring_expenses')
    # ### end Alembic commands ###
