"""plaid item sync cursor

Revision ID: 889bea7abe38
Revises: 51606e172557
Create Date: 2026-07-10 10:03:42.317766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889bea7abe38'
down_revision = '51606e172557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_cursor', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_items', schema=None) as batch_op:
        batch_op.drop_column('sync_cursor')

    # ### end Alembic commands ###
